name: Deploy

on:
  push:
    branches:
      - main

env:
  DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
  DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
  DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
  DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
  DEPLOY_DESTINATION: /srv/www/${{ github.event.repository.name }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create destination directory
        run: |
          mkdir -p $DEPLOY_DESTINATION
      - name: Deploy with rsync
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -p $DEPLOY_PORT" ./ $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DESTINATION
      - name: Build containers
        run: |
          ssh -o StrictHostKeyChecking=no -p $DEPLOY_PORT $DEPLOY_USER@$DEPLOY_HOST "cd $DEPLOY_DESTINATION && make build@prod"
